package logic;

import java.io.Serializable;

/**
 * Represents a reservation/order in the Bistro system.
 * <p>
 * This class is used as a shared data transfer object (DTO) between the client, server,
 * and database layers. It contains reservation details such as date/time, guest count,
 * customer/subscriber information, assigned table, status tracking, and timestamps.
 * </p>
 * <p>
 * The class implements {@link Serializable} to allow sending instances over the network
 * (e.g., via OCSF) between the client and server.
 * </p>
 */
public class Order implements Serializable {

    /**
     * Internal order identifier (typically generated by the database).
     */
    private int order_number;

    /**
     * Reservation date (format depends on the application conventions).
     */
    private String order_date;

    /**
     * Reservation time (format depends on the application conventions).
     */
    private String order_time;

    /**
     * Number of guests included in the reservation.
     */
    private int number_of_guests;

    /**
     * Unique confirmation code provided to the customer for lookup and actions.
     */
    private int confirmation_code;

    /**
     * Subscriber identifier associated with the reservation, or {@code 0} / unused for guest reservations
     * depending on the application conventions.
     */
    private int subscriber_id;

    /**
     * Customer/guest name (or subscriber name as displayed).
     */
    private String customer_name;

    /**
     * Customer phone number used for contact.
     */
    private String customer_phone;

    /**
     * Customer email address used for contact and confirmations.
     */
    private String customer_email;

    /**
     * Timestamp indicating when the order/reservation was placed.
     */
    private String date_of_placing_order;

    /**
     * Assigned table number for the reservation (may be {@code 0} if not assigned).
     */
    private int table_num;

    /**
     * Current status of the order/reservation (e.g., BOOKED, WAITING, SEATED, BILL_SENT, etc.).
     */
    private String order_status;

    /**
     * Timestamp indicating when the status was last updated.
     */
    private String status_datetime;

    /**
     * Indicates whether a reminder message was already sent for this reservation.
     */
    private boolean reminder_sent;

    /**
     * Recorded arrival date/time for the reservation (may be {@code null} if not recorded).
     */
    private String arrival_datetime;

    /**
     * Creates a new {@link Order} instance containing all reservation and tracking fields.
     *
     * @param order_number           internal order identifier (typically DB-generated)
     * @param order_date             reservation date
     * @param order_time             reservation time
     * @param number_of_guests       number of guests
     * @param confirmation_code      unique confirmation code for the customer
     * @param subscriber_id          subscriber identifier (if applicable)
     * @param customer_name          customer/guest name
     * @param customer_phone         customer phone number
     * @param customer_email         customer email address
     * @param date_of_placing_order  timestamp of when the reservation was placed
     * @param table_num              assigned table number (if applicable)
     * @param order_status           current reservation status
     * @param status_datetime        timestamp of last status update
     * @param reminder_sent          whether a reminder has been sent
     * @param arrival_datetime       arrival timestamp (if recorded)
     */
    public Order(int order_number, String order_date, String order_time, int number_of_guests,
                 int confirmation_code, int subscriber_id, String customer_name,
                 String customer_phone, String customer_email, String date_of_placing_order,
                 int table_num, String order_status, String status_datetime,
                 boolean reminder_sent, String arrival_datetime) {

        this.order_number = order_number;
        this.order_date = order_date;
        this.order_time = order_time;
        this.number_of_guests = number_of_guests;
        this.confirmation_code = confirmation_code;
        this.subscriber_id = subscriber_id;
        this.customer_name = customer_name;
        this.customer_phone = customer_phone;
        this.customer_email = customer_email;
        this.date_of_placing_order = date_of_placing_order;
        this.table_num = table_num;
        this.order_status = order_status;
        this.status_datetime = status_datetime;
        this.reminder_sent = reminder_sent;
        this.arrival_datetime = arrival_datetime;
    }

    /**
     * Returns the customer name.
     *
     * @return the customer name
     */
    public String getCustomer_name() {
        return customer_name;
    }

    /**
     * Sets the customer name.
     *
     * @param customer_name the customer name to set
     */
    public void setCustomer_name(String customer_name) {
        this.customer_name = customer_name;
    }

    /**
     * Returns the customer phone number.
     *
     * @return the customer phone number
     */
    public String getCustomer_phone() {
        return customer_phone;
    }

    /**
     * Sets the customer phone number.
     *
     * @param customer_phone the customer phone number to set
     */
    public void setCustomer_phone(String customer_phone) {
        this.customer_phone = customer_phone;
    }

    /**
     * Returns the internal order number.
     *
     * @return the order number
     */
    public int getOrder_number() {
        return order_number;
    }

    /**
     * Sets the internal order number.
     *
     * @param order_number the order number to set
     */
    public void setOrder_number(int order_number) {
        this.order_number = order_number;
    }

    /**
     * Returns the customer email address.
     *
     * @return the customer email
     */
    public String getCustomer_email() {
        return customer_email;
    }

    /**
     * Sets the customer email address.
     *
     * @param customer_email the customer email to set
     */
    public void setCustomer_email(String customer_email) {
        this.customer_email = customer_email;
    }

    /**
     * Returns the reservation date.
     *
     * @return the reservation date
     */
    public String getOrder_date() {
        return order_date;
    }

    /**
     * Sets the reservation date.
     *
     * @param order_date the reservation date to set
     */
    public void setOrder_date(String order_date) {
        this.order_date = order_date;
    }

    /**
     * Returns the reservation time.
     *
     * @return the reservation time
     */
    public String getOrder_time() {
        return order_time;
    }

    /**
     * Sets the reservation time.
     *
     * @param order_time the reservation time to set
     */
    public void setOrder_time(String order_time) {
        this.order_time = order_time;
    }

    /**
     * Returns the number of guests.
     *
     * @return the number of guests
     */
    public int getNumber_of_guests() {
        return number_of_guests;
    }

    /**
     * Sets the number of guests.
     *
     * @param number_of_guests the number of guests to set
     */
    public void setNumber_of_guests(int number_of_guests) {
        this.number_of_guests = number_of_guests;
    }

    /**
     * Returns the confirmation code.
     *
     * @return the confirmation code
     */
    public int getConfirmation_code() {
        return confirmation_code;
    }

    /**
     * Sets the confirmation code.
     *
     * @param confirmation_code the confirmation code to set
     */
    public void setConfirmation_code(int confirmation_code) {
        this.confirmation_code = confirmation_code;
    }

    /**
     * Returns the subscriber identifier.
     *
     * @return the subscriber id
     */
    public int getSubscriber_id() {
        return subscriber_id;
    }

    /**
     * Sets the subscriber identifier.
     *
     * @param subscriber_id the subscriber id to set
     */
    public void setSubscriber_id(int subscriber_id) {
        this.subscriber_id = subscriber_id;
    }

    /**
     * Returns the timestamp of when the reservation was placed.
     *
     * @return the placing timestamp
     */
    public String getDate_of_placing_order() {
        return date_of_placing_order;
    }

    /**
     * Sets the timestamp of when the reservation was placed.
     *
     * @param date_of_placing_order the placing timestamp to set
     */
    public void setDate_of_placing_order(String date_of_placing_order) {
        this.date_of_placing_order = date_of_placing_order;
    }

    /**
     * Returns the assigned table number.
     *
     * @return the table number
     */
    public int getTable_num() {
        return table_num;
    }

    /**
     * Sets the assigned table number.
     *
     * @param tableNum the table number to set
     */
    public void setTable_num(int tableNum) {
        this.table_num = tableNum;
    }

    /**
     * Returns the current reservation status.
     *
     * @return the reservation status
     */
    public String getOrder_status() {
        return order_status;
    }

    /**
     * Sets the current reservation status.
     *
     * @param order_status the reservation status to set
     */
    public void setOrder_status(String order_status) {
        this.order_status = order_status;
    }

    /**
     * Returns the timestamp of the last status update.
     *
     * @return the status timestamp
     */
    public String getStatus_datetime() {
        return status_datetime;
    }

    /**
     * Sets the timestamp of the last status update.
     *
     * @param status_datetime the status timestamp to set
     */
    public void setStatus_datetime(String status_datetime) {
        this.status_datetime = status_datetime;
    }

    /**
     * Returns whether a reminder has been sent.
     *
     * @return {@code true} if a reminder was sent; otherwise {@code false}
     */
    public boolean getReminder_sent() {
        return reminder_sent;
    }

    /**
     * Sets whether a reminder has been sent.
     *
     * @param reminder_sent {@code true} if a reminder was sent; otherwise {@code false}
     */
    public void setReminder_sent(boolean reminder_sent) {
        this.reminder_sent = reminder_sent;
    }

    /**
     * Returns the arrival timestamp for the reservation.
     *
     * @return the arrival timestamp, or {@code null} if not recorded
     */
    public String getArrival_datetime() {
        return arrival_datetime;
    }

    /**
     * Sets the arrival timestamp for the reservation.
     *
     * @param arrival_datetime the arrival timestamp to set
     */
    public void setArrival_datetime(String arrival_datetime) {
        this.arrival_datetime = arrival_datetime;
    }

    /**
     * Returns a string representation of this order for debugging/logging purposes.
     *
     * @return a string representation of the order
     */
    @Override
    public String toString() {
        return "Order [order_number=" + order_number +
                ", order_date=" + order_date +
                ", order_time=" + order_time +
                ", number_of_guests=" + number_of_guests +
                ", confirmation_code=" + confirmation_code +
                ", subscriber_id=" + subscriber_id +
                ", customer_name=" + customer_name +
                ", customer_phone=" + customer_phone +
                ", customer_email=" + customer_email +
                ", date_of_placing_order=" + date_of_placing_order +
                ", table_num=" + table_num +
                ", order_status=" + order_status +
                ", status_datetime=" + status_datetime +
                ", reminder_sent=" + reminder_sent +
                ", arrival_datetime=" + arrival_datetime +
                "]";
    }
}
